 -- 1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE,'YYYY"-"MM"-"DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

 -- 2
 SELECT PROFESSOR_NAME, PROFESSOR_SSN
 FROM TB_PROFESSOR
 WHERE NOT LENGTH(PROFESSOR_NAME) = '3';
 
 -- 3 
 SELECT PROFESSOR_NAME 교수이름, 
    EXTRACT(YEAR FROM SYSDATE)-(1900+SUBSTR(PROFESSOR_SSN,1,2)) 나이
 FROM TB_PROFESSOR
 WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1'
 ORDER BY SUBSTR(PROFESSOR_SSN,1,2) DESC;
 
 -- 4 
 SELECT SUBSTR(PROFESSOR_NAME,2,3) 이름
 FROM TB_PROFESSOR;
 
 -- 5 
 SELECT STUDENT_NO, STUDENT_NAME
 FROM TB_STUDENT
 WHERE EXTRACT(YEAR FROM TO_DATE(ENTRANCE_DATE,'YY/MM/DD'))-EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RR/MM/DD')) = '20';
 
 -- 6
 SELECT TO_CHAR(TO_DATE(20201225), 'DAY') 요일
 FROM DUAL;
 
 ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD';
 -- 7
 SELECT TO_DATE('99/10/11', 'YY/MM/DD')값1, TO_DATE('49/10/11', 'YY/MM/DD')값2,
           TO_DATE('99/10/11', 'RR/MM/DD')값3, TO_DATE('49/10/11', 'RR/MM/DD')값4
 FROM DUAL;
 
 -- 8
 SELECT STUDENT_NO, STUDENT_NAME
 FROM TB_STUDENT
 WHERE NOT SUBSTR(STUDENT_NO,1,1) = 'A';
 
 -- 9
 SELECT ROUND(SUM(POINT)/COUNT(CLASS_NO),1) 평점
 FROM TB_STUDENT S, TB_GRADE G 
 WHERE S.STUDENT_NO = G.STUDENT_NO AND STUDENT_NAME = '한아름';
 
 -- 10
 SELECT DEPARTMENT_NO 학과번호,COUNT(*) 학생수 
 FROM TB_STUDENT
 GROUP BY DEPARTMENT_NO
 ORDER BY DEPARTMENT_NO;

 -- 11 
 SELECT COUNT(*)
 FROM TB_STUDENT
 WHERE COACH_PROFESSOR_NO IS NULL;
 
  SELECT * FROM TB_STUDENT ORDER BY STUDENT_NAME;
 
 -- 12
 SELECT SUBSTR(TERM_NO,1,4), ROUND(AVG(POINT),1)
 FROM TB_STUDENT 
 JOIN TB_GRADE USING (STUDENT_NO)
 WHERE STUDENT_NAME = '김고운'
 GROUP BY SUBSTR(TERM_NO,1,4)
 ORDER BY SUBSTR(TERM_NO,1,4);
 
 -- 13
 SELECT DEPARTMENT_NO 학과코드명, COUNT(DECODE (ABSENCE_YN, 'Y', 'Y')) "휴학생 수"
 FROM TB_STUDENT
 GROUP BY DEPARTMENT_NO
 ORDER BY DEPARTMENT_NO;
 
 -- 14
 SELECT STUDENT_NAME 동일이름, COUNT(*)
 FROM TB_STUDENT
 GROUP BY STUDENT_NAME
 HAVING COUNT(STUDENT_NAME) != '1';
 
 -- 15 (중간집계를 못했어요ㅠ)
 SELECT SUBSTR(TERM_NO,1,4) 년도, SUBSTR(TERM_NO,5,2) 학기, ROUND(AVG(POINT),1)
 FROM TB_GRADE
 WHERE STUDENT_NO = 'A112113'
 GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2))
 ORDER BY SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2);
