-- 1
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, ROWNUM 순위
FROM (SELECT DISTINCT EMP_ID,  EMP_NAME, DEPT_TITLE, JOB_NAME,
                                 HIRE_DATE, (SALARY+SALARY*(NVL(BONUS,0)))*12
          FROM EMPLOYEE
          JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
           JOIN JOB USING (JOB_CODE)
          ORDER BY (SALARY+SALARY*(NVL(BONUS,0)))*12 DESC)
WHERE ROWNUM <=5
ORDER BY ROWNUM;

-- 2
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
GROUP BY DEPT_CODE, DEPT_TITLE
HAVING SUM(SALARY) >(SELECT SUM(SALARY)*0.2
                                 FROM EMPLOYEE);

-- 3
WITH SAL AS(SELECT SALARY
                  FROM EMPLOYEE)
SELECT SUM(SALARY), AVG(SALARY)
FROM SAL;






