 -- 1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE,'YYYY"-"MM"-"DD') 입학년도
FROM TB_CLASS C, TB_STUDENT S
WHERE C.DEPARTMENT_NO = S.DEPARTMENT_NO AND C.DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

 -- 2
 SELECT PROFESSOR_NAME, PROFESSOR_SSN
 FROM TB_PROFESSOR
 WHERE NOT LENGTH(PROFESSOR_NAME) = '3';
 
 ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD';
 
 -- 3 다시
-- SELECT PROFESSOR_NAME 교수이름, EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'YY/MM/DD')) 나이
-- FROM TB_PROFESSOR
-- ORDER BY SUBSTR(PROFESSOR_SSN,1,2);
 
 -- 4 
 SELECT SUBSTR(PROFESSOR_NAME,2,3) 이름
 FROM TB_PROFESSOR;
 
 -- 5 
 SELECT STUDENT_NO, STUDENT_NAME
 FROM TB_STUDENT
 WHERE EXTRACT(YEAR FROM TO_DATE(ENTRANCE_DATE,'YY/MM/DD'))-EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RR/MM/DD')) = '20';
 
 -- 6
 SELECT TO_CHAR(TO_DATE(20201225), 'DAY')
 FROM DUAL;
 
 -- 7
 SELECT TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD'),
           TO_DATE('99/10/11', 'RR/MM/DD'), TO_DATE('49/10/11', 'RR/MM/DD')
 FROM DUAL;
 
 -- 8
 SELECT STUDENT_NO, STUDENT_NAME
 FROM TB_STUDENT
 WHERE NOT SUBSTR(STUDENT_NO,1,1) = 'A';
 
 -- 9
 SELECT ROUND(SUM(POINT)/COUNT(CLASS_NO),1)
 FROM TB_STUDENT S, TB_GRADE G 
 WHERE S.STUDENT_NO = G.STUDENT_NO AND STUDENT_NAME = '한아름';
 
 -- 10
-- SELECT DEPARTMENT_NO 학과번호, 
-- FROM TB_DEPARTMENT, TB_STUDENT
-- GROUP BY ;

 -- 11 
 SELECT COUNT(*)
 FROM TB_STUDENT
 WHERE COACH_PROFESSOR IS NULL;
 
 -- 12
 SELECT SUBSTR(TERM_NO,1,4), ROUND(SUM(POINT)/COUNT(CLASS_NO),1)
 FROM TB_STUDENT S, TB_GRADE G
 GROUP BY SUBSTR(TERM_NO,1,4)
 WHERE S.STUDENT_NO = G.STUDENT_NO
 HAVING STUDENT_NAME = '김고운';
-- 
 -- 13
-- SELECT DEPARTMENT_NO, COUNT(DEPARTMENT_NO)
-- FROM TB_STUDENT
-- GROUP BY DEPARTMENT_NO
-- WHERE ABSENCE_YN = 'Y' ;
 
 -- 14
 SELECT STUDENT_NAME 동일이름, COUNT(*)
 FROM TB_STUDENT
 GROUP BY STUDENT_NAME
 HAVING COUNT(STUDENT_NAME) != '1';
 
 -- 15
 SELECT SUBSTR(TERM_NO,1,4) 년도, SUBSTR(TERM_NO,5,2) 학기, POINT
 FROM TB_GRADE
 GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4));
 
 
 
 
 
 
 
 
 
 
 
 