 --1
 SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
 FROM TB_STUDENT
 ORDER BY STUDENT_NAME;
 
 --2
 SELECT STUDENT_NAME, STUDENT_SSN
 FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y'
 ORDER BY SUBSTR(STUDENT_SSN,1,6) DESC;
 
 -- 3
 SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS 주소
 FROM TB_STUDENT
 WHERE (STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '강원도%')
         AND SUBSTR(STUDENT_NO,1,1) = '9'
 ORDER BY STUDENT_NAME;
 
 --4
 SELECT PROFESSOR_NAME, PROFESSOR_SSN
 FROM TB_PROFESSOR P
 JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO=P.DEPARTMENT_NO)
 WHERE DEPARTMENT_NAME = '법학과'
 ORDER BY SUBSTR(PROFESSOR_SSN,1,6);
 
 --5
 SELECT STUDENT_NO, POINT
 FROM TB_GRADE
 WHERE CLASS_NO = 'C3118100' AND TERM_NO = '200402'
 ORDER BY POINT DESC;
 
 -- 6
 SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
 FROM TB_STUDENT S
 JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
 ORDER BY STUDENT_NAME;
 
 -- 7
 SELECT CLASS_NAME, DEPARTMENT_NAME
 FROM TB_CLASS C
 JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO= D.DEPARTMENT_NO);
 
 -- 8
 SELECT CLASS_NAME, PROFESSOR_NAME
 FROM TB_CLASS C
 JOIN TB_PROFESSOR P ON (C.DEPARTMENT_NO= P.DEPARTMENT_NO)
 ORDER BY PROFESSOR_NAME;
 
 -- 9
-- SELECT S.STUDENT_NO "학번", S.STUDENT_NAME "학생 이름",  SUM(POINT)/COUNT(STUDENT_NAME) "전체 평점"
-- FROM TB_STUDENT S
-- JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
-- JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
-- WHERE DEPARTMENT_NAME = '음악학과'
-- GROUP BY S.STUDENT_NO;

 -- 10
-- SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수
-- FROM TB_STUDENT S
-- JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
-- JOIN TB_PROFESSOR P ON (S.DEPARTMENT_NO = P.DEPARTMENT_NO)
-- WHERE STUDENT_NO = 'A313047';

 -- 11
 SELECT STUDENT_NAME, TERM_NO
 FROM TB_STUDENT S
 JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
 JOIN TB_CLASS C ON(S.DEPARTMENT_NO = C.DEPARTMENT_NO)
 WHERE SUBSTR(TERM_NO,1,4) = '2007' AND CLASS_NAME = '인간관계론';
 
 -- 12
-- SELECT CLASS_NAME, DEPARTMENT_NAME
-- FROM 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 